### ISSUE TITLE
goroutine 116522 [semacquire, 2 minutes]:

### ISSUE THREAD

**Issue by 510908220** [rs/dnstrace#2]
`goroutine 116608 [semacquire, 2 minutes]:
sync.runtime_Semacquire(0x2c51d20c)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/sema.go:56 +0x2e
sync.(*WaitGroup).Wait(0x2c51d200)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/sync/waitgroup.go:129 +0x7a
github.com/rs/dnstrace/client.(*Client).RecursiveQuery(0x1987c770, 0x2b360690, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/rs/dnstrace/client/client.go:124 +0x197
github.com/rs/dnstrace/client.(*Client).lookupHost.func1(0x1987c770, 0x2b360690, 0x2b310d00)
	/home/travis/gopath/src/github.com/rs/dnstrace/client/client.go:230 +0x39
created by github.com/rs/dnstrace/client.(*Client).lookupHost
	/home/travis/gopath/src/github.com/rs/dnstrace/client/client.go:229 +0xe7
`

**Comment by rs** [comment]
How do you reproduce?

**Comment by eur0pa** [comment]
@rs: `dnstrace A baby.asda.com` will lock the system and get stuck in recursive queries

**Comment by kokizzu** [comment]
happened also for `example.com`
